export const PAYMENT_GATEWAY = {
  RAZORPAY: "RAZORPAY",
  PHONEPE: "PHONEPE",
};

export const PAYMENT_STATUS = {
  CREATED: "CREATED",
  PENDING: "PENDING",
  AUTHORIZED: "AUTHORIZED",
  CAPTURED: "CAPTURED",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
  CANCELLED: "CANCELLED",
};

export const PAYMENT_EVENT_SOURCE = {
  CLIENT_VERIFY: "CLIENT_VERIFY",
  WEBHOOK: "WEBHOOK",
  SYSTEM: "SYSTEM",
};

export const ALL_PAYMENT_GATEWAYS = Object.values(PAYMENT_GATEWAY);
export const ALL_PAYMENT_STATUSES = Object.values(PAYMENT_STATUS);
export const ALL_PAYMENT_EVENT_SOURCES = Object.values(PAYMENT_EVENT_SOURCE);

const TRANSITIONS = {
  [PAYMENT_STATUS.CREATED]: new Set([
    PAYMENT_STATUS.PENDING,
    PAYMENT_STATUS.AUTHORIZED,
    PAYMENT_STATUS.CAPTURED,
    PAYMENT_STATUS.FAILED,
    PAYMENT_STATUS.CANCELLED,
  ]),
  [PAYMENT_STATUS.PENDING]: new Set([
    PAYMENT_STATUS.AUTHORIZED,
    PAYMENT_STATUS.CAPTURED,
    PAYMENT_STATUS.FAILED,
    PAYMENT_STATUS.CANCELLED,
  ]),
  [PAYMENT_STATUS.AUTHORIZED]: new Set([
    PAYMENT_STATUS.CAPTURED,
    PAYMENT_STATUS.FAILED,
    PAYMENT_STATUS.REFUNDED,
  ]),
  [PAYMENT_STATUS.CAPTURED]: new Set([PAYMENT_STATUS.REFUNDED]),
  [PAYMENT_STATUS.FAILED]: new Set(),
  [PAYMENT_STATUS.CANCELLED]: new Set(),
  [PAYMENT_STATUS.REFUNDED]: new Set(),
};

export function canTransitionPaymentStatus(fromStatus, toStatus) {
  if (!fromStatus || !toStatus) return false;
  if (fromStatus === toStatus) return true;
  return TRANSITIONS[fromStatus]?.has(toStatus) || false;
}
